version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - '8082:80'
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
  cache:
    image: redis:latest

volumes:
  mysqldata:
